#!/usr/bin/env node
/**
 * Regenerate INDEX.md from manifest.json (single source of truth).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = join(root, "manifest.json");
const indexPath = join(root, "INDEX.md");

const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const entries = manifest.entries ?? [];

function titleCaseFolder(folder) {
  return folder
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function folderFromPath(path) {
  const slash = path.indexOf("/");
  return slash === -1 ? "root" : path.slice(0, slash);
}

/** Preserve first-seen folder order from manifest. */
const groups = new Map();
for (const entry of entries) {
  const folder = folderFromPath(entry.path);
  if (!groups.has(folder)) groups.set(folder, []);
  groups.get(folder).push(entry);
}

const lines = [
  "# Index",
  "",
  "<!-- Generated by `npm run index` from manifest.json — do not edit by hand. -->",
  "",
  "Lean map for agents. Open pages by id/path only when tags match. Prefer `status: active`.",
  "",
];

for (const [folder, group] of groups) {
  lines.push(`## ${titleCaseFolder(folder)}`);
  lines.push("");
  lines.push("| id | path | status | updated | when_to_use | related |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const e of group) {
    const related = Array.isArray(e.related) && e.related.length
      ? e.related.join(", ")
      : "—";
    lines.push(
      `| ${e.id} | \`${e.path}\` | ${e.status ?? "—"} | ${e.updated ?? "—"} | ${e.when_to_use ?? "—"} | ${related} |`,
    );
  }
  lines.push("");
}

writeFileSync(indexPath, lines.join("\n"), "utf8");
console.log(`Wrote ${indexPath} (${entries.length} entries)`);
